# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#
name: OpenWrt-biull

on:
        workflow_dispatch
jobs:

  build_openwrt:

    name: biull

    runs-on: ubuntu-20.04

    steps:
    
      - name: Checkout OpenWrt
        uses: actions/checkout@v4

      - name: check
        run: 
          ls -a
